In [10]:
# rozkład na wartosci singularne
from numpy import array
from scipy.linalg import svd
# macierz
A = array([[3, 1, 1], [-1, 3, 1]])
print("A=",A)
# SVD
U, S, V_T = svd(A)
# lewe wektory własne
print("U=")
print(U)
# wartosci singularne
print("S=")
print(S)
# prawe wektory własne
print("V_T=")
print(V_T)
# tworzenie macierzy diagnolanej
S_diag = array([[3.46410162, 0, 0], [0, 3.16227766, 0]])
S_diag
# rekonstrukcja naszej oryginalnej macierzy A z elementów dekompozycji według wartości osobliwych
# mnożymy nasze macierze od prawej; czyli najpierw mnożone są dwie ostatnie macierze, a wynik mnożymy przez 1 macierz
B = U.dot(S_diag.dot(V_T))
print("Reconstructed matrix:")
print(B)

A= [[ 3  1  1]
 [-1  3  1]]
U=
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
S=
[3.46410162 3.16227766]
V_T=
[[-4.08248290e-01 -8.16496581e-01 -4.08248290e-01]
 [-8.94427191e-01  4.47213595e-01  5.26260748e-16]
 [-1.82574186e-01 -3.65148372e-01  9.12870929e-01]]
Reconstructed matrix:
[[ 3.  1.  1.]
 [-1.  3.  1.]]
