In [1]:
import numpy as np
macierz = np.array([[1, 2, 3],
                    [1, 2, 3],
                    [1, 2, 3]])

print("Numpy Matrix is:")
print(macierz)

wyznacznik = np.linalg.det(macierz)
print(int(wyznacznik))

def wyznacznik_macierzy(a):
    if len(a) == 1:
        liczenie = a[0]
        return liczenie
    elif len(a) == 2:
        liczenie = a[0][0]*a[1][1] - a[1][0]*a[0][1]
        return liczenie
    elif len(a) == 3:
        liczenie = a[0][0]*a[1][1]*a[2][2]+a[1][0]*a[2][1]*a[0][2]+a[2][0]*a[0][1]*a[1][2]-a[0][2]*a[1][1]*a[2][0]-a[1][2]*a[2][1]*a[0][0]-a[2][2]*a[0][1]*a[1][0]
        return liczenie
    
A = [2]
B = [1,2],[2,2]
print(wyznacznik_macierzy(macierz))

Numpy Matrix is:
[[1 2 3]
 [1 2 3]
 [1 2 3]]
0
0
